name: Build zip-installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: 下载源码
      uses: actions/checkout@v4
      
    - name: 安装Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.8'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install plyer
        pip install maliang
        pip install pywebview
        pip install pyinstaller
        
    - name: 使用PyInstaller构建可执行文件（包含资源）
      run: |
        pyinstaller -w -F -i logo.ico --hidden-import plyer.platforms.win.notification zip-installer.py
    - name: 将资源文件复制到dist目录
      run: |
        copy .\uninstall.bat dist\
    - name: 上传构建工件
      uses: actions/upload-artifact@v4
      with:
        name: zip-installer-executable
        path: dist/
        retention-days: 30
